version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building the project"
      - pytest
  post_build:
    commands:
      - echo "Creating deployment package"
      - zip -r deployment_package.zip .

artifacts:
  files:
    - deployment_package.zip
  discard-paths: yes
