version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Zipping deployment package..."
      - mkdir lib
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
    post-build:
      commands:
        - echo "Updating lambda Function..."
        - aws lambda update-function-code --function-name CreateOrder --zip-file fileb://deployment_package.zip
        - echo "DONE!!"


