version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building the project"
      - cd lib
      - zip -r9 ../deployment_package2.zip .
      - cd ..
      - zip -g deployment_package2.zip lambda_function.py
  post_build:
    commands:
      - echo "Creating deployment package"
      - zip -r deployment_package2.zip .
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name CreateOrder --zip-file fileb://deployment_package2.zip
      - echo "DONE!!"

artifacts:
  files:
    - deployment_package2.zip
  discard-paths: yes
